# Generated by Django 5.0.6 on 2024-06-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_entreprise_freelance_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelance',
            name='skills',
            field=models.CharField(max_length=255),
        ),
    ]
