# Generated by Django 5.0.6 on 2024-06-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_managers_remove_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='companyInformation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='curiosityPass',
            field=models.BooleanField(default=False),
        ),
    ]
