# Generated by Django 5.0.6 on 2024-06-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0003_opportunite'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunite',
            name='automatisation',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='opportunite',
            name='bigData',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='opportunite',
            name='creationOutils',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='opportunite',
            name='dashboard',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='opportunite',
            name='design',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='opportunite',
            name='ecommerce',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='opportunite',
            name='integration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='opportunite',
            name='marketingDigital',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='opportunite',
            name='qualite',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='opportunite',
            name='webAnalyse',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='opportunite',
            name='collecte',
            field=models.IntegerField(null=True),
        ),
    ]
