# Generated by Django 5.0.6 on 2024-06-27 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0004_opportunite_automatisation_opportunite_bigdata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=250)),
                ('niveau', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('CahierDesCharges', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discover.cahierdescharges')),
            ],
        ),
    ]
