# Generated by Django 5.0.6 on 2024-06-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0005_tache'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tache',
            name='CahierDesCharges',
        ),
        migrations.AlterField(
            model_name='tache',
            name='description',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='tache',
            name='CahierDesCharges',
            field=models.ManyToManyField(related_name='tache', to='discover.cahierdescharges'),
        ),
    ]
