# Generated by Django 5.0.6 on 2024-06-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_entreprise_webdatapass_entreprise_nombrecdc'),
        ('discover', '0006_remove_tache_cahierdescharges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cahierdescharges',
            name='prixGlobale',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tache',
            name='prixTaches',
            field=models.IntegerField(null=True),
        ),
        migrations.RemoveField(
            model_name='cahierdescharges',
            name='user',
        ),
        migrations.DeleteModel(
            name='Opportunite',
        ),
        migrations.AddField(
            model_name='cahierdescharges',
            name='user',
            field=models.ManyToManyField(related_name='tache', to='accounts.entreprise'),
        ),
    ]
