# Generated by Django 5.0.6 on 2024-06-27 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_entreprise_webdatapass_entreprise_nombrecdc'),
        ('discover', '0007_cahierdescharges_prixglobale_tache_prixtaches_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CahierDesCharges',
            new_name='CahierDeCharge',
        ),
    ]
