# Generated by Django 5.0.6 on 2024-06-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0008_rename_cahierdescharges_cahierdecharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='cahierdecharge',
            name='noteCohereneEntreprise',
            field=models.IntegerField(null=True),
        ),
    ]
