# Generated by Django 5.0.6 on 2024-06-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0009_cahierdecharge_notecohereneentreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='cahierdecharge',
            name='prixGlobaleConcurrents',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tache',
            name='prixTachesConcurrents',
            field=models.IntegerField(null=True),
        ),
    ]
