# Generated by Django 5.0.6 on 2024-06-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0010_cahierdecharge_prixglobaleconcurrents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tache',
            name='niveau',
        ),
        migrations.AddField(
            model_name='cahierdecharge',
            name='justificationNote',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tache',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
