# Generated by Django 5.0.6 on 2024-06-29 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_entreprise_webdatapass_entreprise_nombrecdc'),
        ('discover', '0012_rename_description_tache_descriptiontache_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cahierdecharge',
            old_name='prixGlobale',
            new_name='prixGlobal',
        ),
        migrations.RenameField(
            model_name='cahierdecharge',
            old_name='prixGlobaleConcurrents',
            new_name='prixGlobalConcurrents',
        ),
        migrations.RemoveField(
            model_name='tache',
            name='CahierDesCharges',
        ),
        migrations.AddField(
            model_name='tache',
            name='CahierDeCharge',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='discover.cahierdecharge'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tache',
            name='titreTache',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='cahierdecharge',
            name='user',
        ),
        migrations.AddField(
            model_name='cahierdecharge',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='cahiers_de_charge', to='accounts.entreprise'),
            preserve_default=False,
        ),
    ]
