# Generated by Django 5.0.6 on 2024-07-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0013_rename_prixglobale_cahierdecharge_prixglobal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cahierdecharge',
            name='discover',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
