# Generated by Django 5.0.6 on 2024-07-03 13:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0014_cahierdecharge_discover'),
    ]

    operations = [
        migrations.AddField(
            model_name='cahierdecharge',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tache',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
